### ISSUE TITLE
How to run the code in ReadMe section

### ISSUE THREAD

**Issue by aishwaryagm1999** [xutianyi1999/SimpleWintun#2]
Hi 
Could you please provide the details on how to run the code in Read me that you have given after cargo.toml.
Should I create another main.rs file and paste in it or paste the code in some other file? The code I have mentioned here is pasted below.

use simple_wintun::adapter::WintunAdapter;
let adapter = WintunAdapter::create_adapter("example", "test", "{D4C24D32-A723-DB80-A493-4E32E7883F15}").unwrap();
adapter.set_ipaddr("10.0.0.1", 24).unwrap();
let session = adapter.start_session(4096).unwrap();

**Comment by xutianyi1999** [comment]
i updated the readme

**Comment by aishwaryagm1999** [comment]
Thanks a lot for the prompt response. I have one more issue. I keep getting the error shown below after building and running the main.rs file. my Main.rs file is located inside the src folder itself.

PS C:\Users\Administrator\Desktop\SimpleWintun-master> cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
PS C:\Users\Administrator\Desktop\SimpleWintun-master> cargo run  
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target\debug\simple_wintun.exe`
**thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." }', src\main.rs:10:110
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\simple_wintun.exe` (exit code: 101)**

How do I resolve this error?

**Comment by xutianyi1999** [comment]
please download wintun.dll to target\debug
https://www.wintun.net/

**Comment by aishwaryagm1999** [comment]
I downloaded Winton.dll to the target/debug folder for the correct processor version. Now getting another error

PS C:\Users\Administrator\Desktop\SimpleWintun-master> cargo run  
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target\debug\simple_wintun.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." }', src\main.rs:12:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\simple_wintun.exe` (exit code: 101)

**Comment by xutianyi1999** [comment]
It's my fault. Change 4096 to 0x20000.
Rings capacity must be between 0x20000 and 0x4000000 must be a power of two

**Comment by aishwaryagm1999** [comment]
Thanks. It works now.
